version: '3.3'

services:
  postgres:
    image: postgres:13.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-imdd}
    networks:
      - postgres-network
    restart: unless-stopped


networks:
  postgres-network: