version: '3.3'

services:
  postgres:
    image: postgres:13.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-imdd}
    networks:
      - postgres-network
    restart: unless-stopped

  imdd_clone:
    image: imdd:v3
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/imdd
    depends_on:
      - postgres
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - "./servers.json:/pgadmin4/servers.json"
    networks:
      - postgres-network
    restart: unless-stopped


networks:
  postgres-network: